# Generated by Django 4.2.6 on 2023-11-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Customer First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Customer Last Name')),
                ('national_ID', models.CharField(max_length=10, unique=True, verbose_name='Customer national ID')),
                ('contact_number', models.CharField(max_length=12, unique=True, verbose_name='Customer Contact number')),
                ('gender', models.CharField(max_length=10, verbose_name='Customer Gender')),
                ('assets', models.IntegerField(verbose_name='Customer Assets To Purchase')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Customer Email')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Manager First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Manager Last Name')),
                ('national_ID', models.CharField(max_length=10, unique=True, verbose_name='Manager national ID')),
                ('contact_number', models.CharField(max_length=12, unique=True, verbose_name='Manager Contact number')),
                ('gender', models.CharField(max_length=10, verbose_name='Manager Gender')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Manager Email')),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='', verbose_name='Concerto Preview File')),
                ('tempo', models.IntegerField(verbose_name='preview tempo')),
                ('quality', models.CharField(max_length=1000, verbose_name='Preview Quality')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Seller First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Seller Last Name')),
                ('national_ID', models.CharField(max_length=10, unique=True, verbose_name='Seller national ID')),
                ('contact_number', models.CharField(max_length=12, unique=True, verbose_name='Seller Contact number')),
                ('gender', models.CharField(max_length=10, verbose_name='Seller Gender')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Seller Email')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holysheet.manager', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Concerto Name')),
                ('concerto_ID', models.CharField(max_length=10, unique=True, verbose_name='concerto ID')),
                ('price', models.IntegerField(verbose_name='Concerto Price')),
                ('concerto_file', models.FileField(unique=True, upload_to='', verbose_name='Concerto File Path')),
                ('score', models.IntegerField(max_length=2, verbose_name='Concerto Score')),
                ('genre', models.CharField(choices=[('POP', 'pop'), ('JAZZ', 'jazz'), ('INSTRUMENTAL', 'instrumental'), ('ROCK', 'rock'), ('ELECTRONIC', 'electronic'), ('METAL', 'metal'), ('RAP', 'rap')], max_length=1000, verbose_name='concerto genre')),
                ('description', models.CharField(max_length=1000, verbose_name='Concerto Description')),
                ('quality', models.CharField(max_length=1000, verbose_name='Concerto Quality')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holysheet.seller', unique=True)),
                ('preview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='holysheet.preview')),
            ],
        ),
    ]
