# Generated by Django 4.2.6 on 2023-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holysheet', '0002_remove_customer_first_name_remove_customer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='0000000', max_length=100, verbose_name='Customer First name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='0000000', max_length=100, verbose_name='Customer Gender'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='0000000', max_length=100, verbose_name='Customer Last name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(default='0000000', max_length=100, verbose_name='Seller First name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='gender',
            field=models.CharField(default='0000000', max_length=100, verbose_name='Seller Gender'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default='0000000', max_length=100, verbose_name='Seller Last name'),
        ),
    ]
