# Generated by Django 4.2.6 on 2023-11-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holysheet', '0003_customer_first_name_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='assets',
            field=models.IntegerField(default='0000000', verbose_name='Customer Assets To Purchase'),
        ),
    ]
