# Generated by Django 4.2.6 on 2024-01-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holysheet', '0004_alter_customer_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='followers_num',
            field=models.IntegerField(default=0, max_length=100, verbose_name='followers'),
        ),
        migrations.AddField(
            model_name='customer',
            name='followings_num',
            field=models.IntegerField(default=0, max_length=100, verbose_name='followings'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default=0, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='followers_num',
            field=models.IntegerField(default=0, max_length=100, verbose_name='followers'),
        ),
        migrations.AddField(
            model_name='seller',
            name='followings_num',
            field=models.IntegerField(default=0, max_length=100, verbose_name='followings'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(default=0, upload_to=None),
            preserve_default=False,
        ),
    ]
