# Generated by Django 4.2.6 on 2024-01-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holysheet', '0006_remove_customer_followers_num_seller_posts_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='../../vue-holysheet/assets/profile-icon.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(default='../../vue-holysheet/assets/profile-icon.jpg', upload_to=None),
        ),
    ]
