# Generated by Django 4.2.6 on 2024-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holysheet', '0007_alter_customer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_logged_in',
            field=models.BooleanField(default=False, verbose_name='logged_in'),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_logged_in',
            field=models.BooleanField(default=False, verbose_name='logged_in'),
        ),
    ]
