# Generated by Django 4.2.9 on 2024-01-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0008_customer_is_logged_in_seller_is_logged_in"),
        ("holysheet", "0009_alter_concerto_owner"),
    ]

    operations = []
