# Generated by Django 4.2.9 on 2024-01-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0010_merge_20240131_1144"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="is_logged_in",),
        migrations.RemoveField(model_name="seller", name="is_logged_in",),
    ]
