# Generated by Django 4.2.9 on 2024-01-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0012_alter_concerto_concerto_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="concerto", name="concerto_ID",),
    ]
