# Generated by Django 4.2.9 on 2024-01-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0013_remove_concerto_concerto_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="concerto",
            name="composer",
            field=models.CharField(
                default=0, max_length=100, verbose_name="Concerto Composer"
            ),
            preserve_default=False,
        ),
    ]
