# Generated by Django 4.2.9 on 2024-01-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0014_concerto_composer"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="saved_concertos",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="holysheet.concerto"
            ),
        ),
    ]
