# Generated by Django 4.2.9 on 2024-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0015_seller_saved_concertos"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="posted_concertos",
            field=models.ManyToManyField(
                blank=True, related_name="posted_by", to="holysheet.concerto"
            ),
        ),
    ]
