# Generated by Django 4.2.6 on 2024-01-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holysheet', '0017_customer_saved_concertos'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='assets',
            field=models.IntegerField(default='0000000', verbose_name='Customer Assets To Purchase'),
        ),
    ]
