# Generated by Django 4.2.9 on 2024-02-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0018_seller_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="profile_picture",
            field=models.ImageField(default="profile-icon.jpg", upload_to=None),
        ),
    ]
