# Generated by Django 4.2.6 on 2024-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holysheet', '0018_seller_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='followers',
            field=models.ManyToManyField(to='holysheet.customer'),
        ),
    ]
