# Generated by Django 4.2.6 on 2024-02-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holysheet', '0019_seller_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='followers',
            new_name='Customer_followers',
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_followers',
            field=models.ManyToManyField(to='holysheet.seller'),
        ),
    ]
