# Generated by Django 4.2.9 on 2024-02-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0019_alter_seller_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="concerto",
            name="concerto_file_pdf",
            field=models.FileField(
                default=0, upload_to="", verbose_name="Concerto File Path Pdf"
            ),
            preserve_default=False,
        ),
    ]
