# Generated by Django 4.2.9 on 2024-02-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holysheet", "0020_concerto_concerto_file_pdf"),
        ("holysheet", "0020_rename_followers_seller_customer_followers_and_more"),
    ]

    operations = []
